/**
 * Offline regenerator for src/engine/maps/tips.ts — one opening tip per level,
 * from that level's map data. NOT part of the build; run by hand:
 *
 *   ANTHROPIC_API_KEY=sk-... npx tsx scripts/gen-tips.ts
 *
 * The committed tips are hand-authored to the same spec, so a missing key
 * never blocks anyone — this just refreshes them.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import Anthropic from '@anthropic-ai/sdk';
import { LEVELS } from '../src/engine/maps/registry';
import { SPRITE_SIZE } from '../src/engine/constants';
import type { LevelDefinition } from '../src/engine/types';

const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'src', 'engine', 'maps', 'tips.ts');

const SYSTEM = [
    'You write a one-line opening tip for a level of a retro NES tank game (Battle City clone).',
    'STYLE: ALL-CAPS, English, one full sentence, <= 12 words, arcade-manual voice.',
    'It must reference something concrete about THIS map (a wall, the base approach, cover, open ground).',
    'Output ONLY the sentence — no quotes, no label.',
].join(' ');

/** A compact readable render of the tile grid for the prompt. */
const asciiMap = (level: LevelDefinition): string => {
    const eagle = new Set(level.flagPosition.map(([r, c]) => `${r},${c}`));
    const spawns = new Set(level.tankSpawns.map((s) => `${s.position[1] / SPRITE_SIZE},${s.position[0] / SPRITE_SIZE}`));
    const players = new Set(level.playerStarts.map((s) => `${s.position[1] / SPRITE_SIZE},${s.position[0] / SPRITE_SIZE}`));
    return level.tiles
        .map((row, r) =>
            row
                .map((t, c) => {
                    if (eagle.has(`${r},${c}`)) return '@';
                    if (spawns.has(`${r},${c}`)) return 'E';
                    if (players.has(`${r},${c}`)) return 'P';
                    if (t === 0) return '.';
                    if (t === 1) return ',';       // shelter/bush
                    if (t >= 5 && t < 6) return '#'; // brick wall
                    if (t >= 6 && t < 7) return 'X'; // rock (indestructible)
                    if (t === 7) return '~';       // water
                    return '?';
                })
                .join(''),
        )
        .join('\n');
};

const client = new Anthropic();

const genTip = async (level: LevelDefinition, index: number): Promise<string> => {
    const res = await client.messages.create({
        model: 'claude-haiku-4-5',
        max_tokens: 60,
        system: SYSTEM,
        messages: [{
            role: 'user',
            content:
                `Level ${index + 1}. Legend: .=open ,=bush #=brick X=rock ~=water @=eagle base P=player start E=enemy spawn.\n\n` +
                asciiMap(level),
        }],
    });
    return res.content
        .filter((b) => b.type === 'text')
        .map((b) => b.text)
        .join('')
        .trim()
        .replace(/^["']|["']$/g, '')
        .toUpperCase();
};

const main = async () => {
    const tips: string[] = [];
    for (let i = 0; i < LEVELS.length; i++) {
        process.stdout.write(`  level ${i + 1}… `);
        tips.push(await genTip(LEVELS[i], i));
        console.log(tips[i]);
    }

    const body = `/**
 * One opening tip per level, shown on the STAGE transition. Regenerated by
 * scripts/gen-tips.ts from the map data via Claude. Indexed by level index —
 * must stay \`LEVELS.length\` long (enforced by tips.test.ts).
 */
export const TIPS: readonly string[] = [
${tips.map((t) => `    ${JSON.stringify(t)},`).join('\n')}
];

/** The tip for \`levelIndex\`, or '' if none (a map added without a tip). */
export const tipFor = (levelIndex: number): string => TIPS[levelIndex] ?? '';
`;
    writeFileSync(OUT, body);
    console.log(`\nwrote ${OUT}`);
};

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
